### ISSUE TITLE
on_error callback seems to disappear, causing undefined coderef errors

### ISSUE THREAD

**Issue by FGasper** [vlet/p5-Protocol-HTTP2#7]
A long-running stream can generate a condition the `on_cancel` callback disappears.

I don’t have a repro setup now because I fixed it locally. If you’d like I can try to put something together, but the fix seems pretty obvious.

**Comment by vlet** [comment]
Fix is obvious, but i'd like to reproduce bug. If you could help me with testcase, that'd be great.

**Comment by vlet** [comment]
Ok, i was able to reproduce it. Stream object had destroyed before received reply from a client.

**Comment by vlet** [comment]
Thanks, merged.
